###############################################################################
#  Repository: ${IMAGE}/mucoll-sim
#  Tag:        ${VERSION}-alma9
###############################################################################

FROM ghcr.io/key4hep/key4hep-externals:main

ARG MUCOLL_SHA=e49a0639ff987a84fa0c6263e068776f9d7b6f67
ARG GITHUB_REPOSITORY=kkrizka/mucoll-spack

# Adding repository: MuColl
RUN source /opt/setup_spack.sh && \
    REPOPATH=${SPACK_ROOT}/var/mucoll-spack && \
    git clone https://github.com/${GITHUB_REPOSITORY} ${REPOPATH} && \
    cd ${REPOPATH} && \
    git checkout ${MUCOLL_SHA} && \
    cd -

# Apply our patches to spack
COPY apply_patches.sh ./apply_patches.sh

RUN source /opt/setup_spack.sh && \
    ./apply_patches.sh ${SPACK_ROOT}/var/mucoll-spack

# Add the package repositories
RUN source /opt/setup_spack.sh && \
    spack repo add --scope system ${SPACK_ROOT}/var/mucoll-spack

# Create the release environment
RUN source /opt/setup_spack.sh && \
    cd ${SPACK_ROOT}/var/mucoll-spack/environments/mucoll-release && \
    spack env activate . && \
    cd - && \
    echo "source /opt/setup_spack.sh" > ${HOME}/setup_env.sh && \
    echo "cd ${SPACK_ROOT}/var/mucoll-spack/environments/mucoll-release" >> ${HOME}/setup_env.sh && \
    echo "spack env activate ." >> ${HOME}/setup_env.sh && \
    echo "cd -" >> ${HOME}/setup_env.sh && \
    echo "spack env status" >> ${HOME}/setup_env.sh

# Concretizing the MuColl stack reusing system packages as external
RUN source ${HOME}/setup_env.sh && \
    spack concretize --reuse

# Installing fragments of dependency tree in separate layers for cached debugging
ENV SPACK_INSTALL_OPTS="--only-concrete --no-add --fail-fast"

RUN source ${HOME}/setup_env.sh && \
    spack spec -NIt && \
    spack install ${SPACK_INSTALL_OPTS} && \
    spack clean -a

RUN source ${HOME}/setup_env.sh && \
    MUCOLL_STACK_PATH=$(spack find --format "{prefix}" mucoll-stack) && \
    echo -e "\e[0malias setup_mucoll=\"source ${MUCOLL_STACK_PATH}/setup.sh\"" >> /etc/profile.d/aliases.sh

# Setting up users to be used for the local environment setup
RUN useradd --shell /bin/bash --create-home mucoll
USER mucoll
WORKDIR /home/mucoll

ENTRYPOINT ["/bin/bash", "--login"]

