###############################################################################
#  Repository: ${IMAGE}/mucoll-sim
#  Tag:        ${VERSION}-alma9
###############################################################################

ARG OS=alma9
FROM ghcr.io/key4hep/key4hep-externals-${OS}:2025-08-05-mucoll

ARG MUCOLL_SHA=e49a0639ff987a84fa0c6263e068776f9d7b6f67
ARG GITHUB_REPOSITORY=muoncollidersoft/mucoll-spack

# Adding repository: MuColl
RUN . /opt/setup_spack.sh && \
    REPOPATH=${SPACK_ROOT}/var/mucoll-spack && \
    git clone https://github.com/${GITHUB_REPOSITORY} ${REPOPATH} && \
    cd ${REPOPATH} && \
    git checkout ${MUCOLL_SHA} && \
    cd -

# Apply our patches to spack
RUN . /opt/setup_spack.sh && \
    REPOPATH=${SPACK_ROOT}/var/mucoll-spack && \
    cd /opt/spack && \
    . ${REPOPATH}/.cherry-pick && \
    cd -

# Add the package repositories
ARG SPACK_BUILDCACHE
ARG OCI_USERNAME
RUN --mount=type=secret,id=ocipass \
    OCI_PASSWORD=$(cat /run/secrets/ocipass) && \
    . /opt/setup_spack.sh && \
    spack repo add --scope system ${SPACK_ROOT}/var/mucoll-spack && \
    if [ -n "${SPACK_BUILDCACHE}" ]; then \
        spack mirror remove local-buildcache || true; \
        spack mirror add --oci-username "${OCI_USERNAME}" --oci-password "${OCI_PASSWORD}" --unsigned --autopush local-buildcache "${SPACK_BUILDCACHE}";\
    fi

# Create the release environment
RUN . /opt/setup_spack.sh && \
    cd ${SPACK_ROOT}/var/mucoll-spack/environments/mucoll-release && \
    spack env activate . && \
    cd - && \
    echo ". /opt/setup_spack.sh" > ${HOME}/setup_env.sh && \
    echo "cd ${SPACK_ROOT}/var/mucoll-spack/environments/mucoll-release" >> ${HOME}/setup_env.sh && \
    echo "spack env activate ." >> ${HOME}/setup_env.sh && \
    echo "cd -" >> ${HOME}/setup_env.sh && \
    echo "spack env status" >> ${HOME}/setup_env.sh

# Concretizing the MuColl stack reusing system packages as external
RUN . ${HOME}/setup_env.sh && \
    spack info conformaltracking && \
    spack find Conformaltracking && \
    spack concretize --reuse

# Installing fragments of dependency tree in separate layers for cached debugging
ENV SPACK_INSTALL_OPTS="--only-concrete --no-add --fail-fast"

RUN . ${HOME}/setup_env.sh && \
    spack spec -NIt && \
    spack install ${SPACK_INSTALL_OPTS} && \
    spack clean -a

RUN . ${HOME}/setup_env.sh && \
    MUCOLL_STACK_PATH=$(spack find --format "{prefix}" mucoll-stack) && \
    MUCOLL_STACK_PATH_CLEANED=$(echo ${MUCOLL_STACK_PATH} | sed -E 's/\x1b\[[0-9;]*m//g') && \
    echo "alias setup_mucoll=\". ${MUCOLL_STACK_PATH_CLEANED}/setup.sh\"" >> /etc/profile.d/aliases.sh

# Setting up users to be used for the local environment setup
RUN useradd --shell /bin/bash --create-home mucoll
USER mucoll
WORKDIR /home/mucoll

ENTRYPOINT ["/bin/bash", "--login"]

